/*
 * Copyright (c) 2018 zhtlab
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit
 * persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _USB_HID_KEYS_H_
#define _USB_HID_KEYS_H_
enum {
  KEYBOARD_LCTRL        = 0x01,
  KEYBOARD_LSHIFT       = 0x02,
  KEYBOARD_LALT         = 0x04,
  KEYBOARD_LGUI         = 0x08,
  KEYBOARD_RCTRL        = 0x10,
  KEYBOARD_RSHIFT       = 0x20,
  KEYBOARD_RALT         = 0x40,
  KEYBOARD_RGUI         = 0x80,
};
enum {
  KEYBOARD_NOEVENT = 0,
  KEYBOARD_ERRROLLOVER,
  KEYBOARD_ERRPOSTFAIL,
  KEYBOARD_ERRUNDEF,
  KEYBOARD_A = 4,
  KEYBOARD_B,
  KEYBOARD_C,
  KEYBOARD_D,
  KEYBOARD_E,
  KEYBOARD_F,
  KEYBOARD_G,
  KEYBOARD_H,
  KEYBOARD_I,
  KEYBOARD_J,
  KEYBOARD_K,
  KEYBOARD_L,
  KEYBOARD_M,
  KEYBOARD_N,
  KEYBOARD_O,
  KEYBOARD_P,
  KEYBOARD_Q,
  KEYBOARD_R,
  KEYBOARD_S,
  KEYBOARD_T,
  KEYBOARD_U,
  KEYBOARD_V,
  KEYBOARD_W,
  KEYBOARD_X,
  KEYBOARD_Y,
  KEYBOARD_Z,
  KEYBOARD_1 = 0x1e,
  KEYBOARD_2,
  KEYBOARD_3,
  KEYBOARD_4,
  KEYBOARD_5,
  KEYBOARD_6,
  KEYBOARD_7,
  KEYBOARD_8,
  KEYBOARD_9,
  KEYBOARD_0,
  KEYBOARD_ENTER = 0x28,
  KEYBOARD_ESCAPE,
  KEYBOARD_BS,
  KEYBOARD_TAB,
  KEYBOARD_SPACE,
  KEYBOARD_MINUS,
  KEYBOARD_EQUAL,
  KEYBOARD_LEFTBRACE,
  KEYBOARD_RIGHTBRACE,
  KEYBOARD_BACKSLASH,
  KEYBOARD_HASHTILDE,
  KEYBOARD_SEMICOLON,
  KEYBOARD_APOSTROPHE,
  KEYBOARD_GRAVE,
  KEYBOARD_COMMA,
  KEYBOARD_DOT,
  KEYBOARD_SLASH,
  KEYBOARD_CAPSLOCK,
  KEYBOARD_F1 = 0x3a,
  KEYBOARD_F2,
  KEYBOARD_F3,
  KEYBOARD_F4,
  KEYBOARD_F5,
  KEYBOARD_F6,
  KEYBOARD_F7,
  KEYBOARD_F8,
  KEYBOARD_F9,
  KEYBOARD_F10,
  KEYBOARD_F11,
  KEYBOARD_F12,
  KEYBOARD_PRINTSCREEN = 0x46,
  KEYBOARD_SCROLLLOCK,
  KEYBOARD_PAUSE,
  KEYBOARD_INSERT,
  KEYBOARD_HOME,
  KEYBOARD_PAGEUP,
  KEYBOARD_DELETEFW,
  KEYBOARD_END,
  KEYBOARD_PAGEDOWN,
  KEYBOARD_RIGHTARROW,
  KEYBOARD_LEFTARROW,
  KEYBOARD_DOWNARROW,
  KEYBOARD_UPARROW,
  KEYPAD_NUMLOCK = 0x53,
  KEYPAD_SLASH,
  KEYPAD_ASTERISK,
  KEYPAD_MINUS,
  KEYPAD_PLUS,
  KEYPAD_ENTER,
  KEYPAD_1,
  KEYPAD_2,
  KEYPAD_3,
  KEYPAD_4,
  KEYPAD_5,
  KEYPAD_6,
  KEYPAD_7,
  KEYPAD_8,
  KEYPAD_9,
  KEYPAD_0,
  KEYPAD_DOT,   /* DELETE */
  KEYBOARD_NONSU_BACKSLASH,
  KEYBOARD_APP,
  KEYBOARD_POWER,
  KEYPAD_EQUAL,
};

#endif
